### PR TITLE
Handling malformed JSON response exception

### PR DESCRIPTION
**Pull request by vinkaga**
Fixes crash due to malformed JSON in response.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Can you give an example of request you are making which returns a malformed json.

Note: This is a breaking change and behaves differently from the client side js sdk. Will require a valid reason before we can merge this in.

**Comment by dejanr** [comment]
It doesn't matter, we should always wrap JSON.parse inside try catch block.

+1 for this change

**Comment by prabirshrestha** [comment]
as i said earlier, we need to be able to reproduce the bug before we merge it in. can u give an example when the server returns a malformed json.

**Comment by dejanr** [comment]
Here are couple of errors we get from your lib, and you could reproduce it with any malformed json response.

```
SyntaxError: Unexpected token <
File null, in Object.parse at line null
File [as _callback] (/var/www/.../www/node_modules/fb/fb.js, in Request.oauthRequest at line 312
File /var/www/.../www/node_modules/fb/node_modules/request/main.js, in Request.init.self.callback at line 120
File events.js, in Request.EventEmitter.emit at line 91
File /var/www/.../www/node_modules/fb/node_modules/request/main.js, in  at line 555
File events.js, in Request.EventEmitter.emit at line 88
File /var/www/.../www/node_modules/fb/node_modules/request/main.js, in IncomingMessage.Request.start.self.req.self.httpModule.request.buffer at line 517
File events.js, in IncomingMessage.EventEmitter.emit at line 115
File http.js, in IncomingMessage._emitEnd at line 366
File [as onMessageComplete] (http.js, in HTTPParser.parserOnMessageComplete at line 149
File [as ondata] (http.js, in CleartextStream.socketOnData at line 1366
```

```
SyntaxError: Unexpected end of input
File null, in Object.parse at line null
File [as _callback] (/var/www/.../www/node_modules/fb/fb.js, in Request.oauthRequest at line 312
File /var/www/.../www/node_modules/fb/node_modules/request/main.js, in Request.init.self.callback at line 120
File events.js, in Request.EventEmitter.emit at line 91
File /var/www/.../www/node_modules/fb/node_modules/request/main.js, in  at line 555
File events.js, in Request.EventEmitter.emit at line 88
File /var/www/.../www/node_modules/fb/node_modules/request/main.js, in IncomingMessage.Request.start.self.req.self.httpModule.request.buffer at line 517
File events.js, in IncomingMessage.EventEmitter.emit at line 115
File http.js, in IncomingMessage._emitEnd at line 366
File http.js, in null at line 1306
```

**Comment by dejanr** [comment]
And its hard to handle it, cause it raise exception, and you don't return error callback, so we cant handle it well.

**Comment by prabirshrestha** [comment]
Can you also mention the api call that produces that error. `FB.api(....)` rather then just the stack trace.

Facebook should always return a json value. if they are returning something else, will need to report it as a bug on their side too.

**Comment by dejanr** [comment]
I am fascinated where this is going. Do whatever you feel its best for your library, but i would not use it cause it raise exception and stops my program running instead of sending me back error callback.

Good luck.

**Comment by prabirshrestha** [comment]
I would definitely would love to add a try..catch. But I'm curious as to why you are getting the non-json response. is it fb returning non json response? or some proxy server that is causing the problem. I would like to know the details.

I'm not being able to reproduce this bug. Can you provide a sample code that reproduces the bug.

`SyntaxError: Unexpected token <` shows that you are getting something like `<html>`.

The reason I'm asking is because we had similar problems. https://graph.facebook.com/i_dont_exist used to return exception json messages but 200ok. After filling a bug in fb it was fixed to return 404. Even though this issue ios absolutely valid and would like to merge it, I would like to know if this is a bug in fb side too, so we can file it.

**Comment by vinkaga** [comment]
Prabir,

FB seems to return incomplete response occasionally. I have captured it
before but don't have it with me at the moment. When I capture it again, I
will share.

Vinay

On Fri, Jan 4, 2013 at 8:14 AM, Prabir Shrestha notifications@github.comwrote:

> I would definitely would love to add a try..catch. But I'm curious as to
> why you are getting the non-json response. is it fb returning non json
> response? or some proxy server that is causing the problem. I would like to
> know the details.
> 
> I'm not being able to reproduce this bug. Can you provide a sample code
> that reproduces the bug.
> 
> SyntaxError: Unexpected token < shows that you are getting something like
> <html>.
> 
> The reason I'm asking is because we had similar problems.
> https://graph.facebook.com/i_dont_exist used to return exception json
> messages but 200ok. After filling a bug in fb it was fixed to return 404.
> Even though this issue ios absolutely valid and would like to merge it, I
> would like to know if this is a bug in fb side too, so we can file it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thuzi/facebook-node-sdk/pull/27#issuecomment-11888360.

## 

Vinay Agarwal
vinkaga@gmail.com
408-480-9688

**Comment by prabirshrestha** [comment]
This is the first time I'm hearing FB returns a partial response. If FB does return partial response it could either be their bug or bug in `request` module though we should be handling this too.

I could reproduce similar error but not exact.

``` js
var FB = require('fb');

FB.api('', function(res){
    console.log(res);
});
```

It happens when path is empty.

```
undefined:1
<!DOCTYPE html>
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request.oauthRequest [as _callback] (/Users/prabirshrestha/Desktop/untitled folder/node_modules/fb/fb.js:296:29)
    at Request.init.self.callback (/Users/prabirshrestha/Desktop/untitled folder/node_modules/fb/node_modules/request/main.js:120:22)
    at Request.EventEmitter.emit (events.js:99:17)
    at Request.<anonymous> (/Users/prabirshrestha/Desktop/untitled folder/node_modules/fb/node_modules/request/main.js:555:16)
    at Request.EventEmitter.emit (events.js:96:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/Users/prabirshrestha/Desktop/untitled folder/node_modules/fb/node_modules/request/main.js:517:14)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
```

@vinkaga could you update the code based on the comments I posted before I can merge it.

**Comment by lookfirst** [comment]
For what it is worth, sometimes fb api calls fail and returns an html page. If you try the same call again, it generally succeeds.

**Comment by prabirshrestha** [comment]
@lookfirst I'm waiting for @vinkaga to update the code based on the code reviews before I can merge this PR.

**Comment by lookfirst** [comment]
I just got one of those errors and managed to capture the html. It looks like this:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
   xml:lang="en" lang="en" id="facebook">
  <head>
    <title>Facebook | Error</title>
    <meta http-equiv="Content-Type"  content="text/html; charset=utf-8" />
    <meta http-equiv="Cache-Control" content="no-cache" />
    <meta name="robots"              content="noindex,nofollow" />
    <style type="text/css">
      html, body {
        margin:       0px;
        padding:      0px;
        text-align:   center;
        font-family:  "Lucida Grande", "Tahoma", "Verdana", "Arial", sans-serif;
        color:        #333333;
      }

      a.menu {
        margin:     auto;
        position:   relative;
        display:    block;
        width:      964px;
        height:     29px;
        background: #3B5998 url('https://s-static.ak.fbcdn.net/common/error.png')
                    top center no-repeat;
      }

      .core {
        text-align: left;
        margin:     auto;
        width:      904px;
        padding:    1em 0em;
      }

      h1 {
        font-size:  18px;
      }

      p {
        font-size:  13px;
      }

      .footer {
        border-top: 1px solid #DDDDDD;
        color:      #777777;
        float:      left;
        width:      904px;
        padding:    5px 8px 6px 0;
        font-size:  11px;
      }
    </style>
    <script type="text/javascript" charset="utf-8">
      function back() {
        if (1 < history.length) {
          history.back();
          return false;
        }
        return true;
      }
    </script>
  </head>
  <body>
    <a class="menu" href="http://www.facebook.com/"></a>
    <div class="core">
      <h1>Sorry, something went wrong.</h1>
      <p>We're working on getting this fixed as soon as we can.</p>
      <p><a onclick="return back();" href="http://www.facebook.com/">Go Back</a></p>
      <div class="footer" id="pagefooter_copyright">
        Facebook &copy;
        2012
        &#183;
        <a href="http://www.facebook.com/help/">Help</a>
      </div>
    </div>
  </body>
</html>
```

**Comment by prabirshrestha** [comment]
@lookfirst could you open a bug in https://developers.facebook.com/bugs/ and also reference this issue. Feel free to send a new PR with the corrected code review.

**Comment by lookfirst** [comment]
Why would I do that? It is a temporary FB failure. I just retry it and it works. The real issue is in this code... when JSON.parse() throws an exception, just retry.

**Comment by prabirshrestha** [comment]
the issue is in both. fb should return json error.

i'm working on some other project. so feel free to send a PR if you want it earlier.

**Comment by prabirshrestha** [comment]
fixed by #29

**Pull request closed without merging**
